<Label>
    font_name: 'database/yahei_mono.ttf'
    color: 0, 0, 0, 1

<SummaryCard>
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            # self here refers to the widget i.e FloatLayout
            pos: self.pos
            size: self.size
    rows: 2

    GridLayout:
        cols: 1
        size_hint_y: 3

        Button:
            text: "ON"
            on_press: root.tik(tar=resutBox)

    FloatLayout:
        id: resutBox
        size_hint_y: 7
